name: dev-build

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["ci-full"]
    types: [completed]

jobs:
  build-and-push:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/quesosbartolome:dev -f docker/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/quesosbartolome:dev

      - name: Publish docker-compose.yml
        run: |
          sed -i "s|quesosbartolome:[^ ]*|quesosbartolome:dev|g" docker/docker-compose-dev.yml
          
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/quesosbartolome-compose:dev --file - . <<DOCKERFILE
          FROM scratch
          COPY docker/docker-compose-dev.yml /docker-compose-dev.yml
          DOCKERFILE
          
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/quesosbartolome-compose:dev

          DOCKERFILE
          
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/quesosbartolome-compose:dev

